- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
- Move plugin to my source github
> Bump V 14.6

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickEcmInfo.py
- usr/lib/enigma2/python/Components/Renderer/RaedQuickSignalPicEmuF.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
- [Converter + Rendere] Update some files for python 3.11
- Fix Emu name + picon name for OpenVix and Egami images
> Bump V15.1

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/screens/skinFHD.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/screens/skinHD.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/configs.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
Try to solve the font conflict changing with plugin [ArabicSavior](https://github.com/fairbird/ArabicSavior)
> Bump V15.2

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/compat.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
Drop python-six for py2 images
> Bump V15.5

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/configs.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V15.7

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickWeather.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/configs.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V15.8

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V15.9

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickSignalCaidInfo2.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.0

- installer.sh
- usr/lib/enigma2/python/Components/Renderer/RaedQuickSignalPiconUni.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.1

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.2

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickSignalText.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
TypeError: '<' not supported between instances of 'NoneType' and 'int'
> Bump V16.3

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickSignalText.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.4

- installer.sh
- usr/lib/enigma2/python/Components/Renderer/RaedQuickSignalPiconUni.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.7

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/compat.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V16.8

- installer.sh
- usr/lib/enigma2/python/Components/Converter/RaedQuickEcmInfo.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V17.0

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
- Fix KeyError: 'startupservice'
> Bump V17.1

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V17.2

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V17.3

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V17.4

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
> Bump V17.5

- installer.sh
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/screens/skinFHD.py
- usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/tools/version
* Remove (valueFont) from skin some images does not use it
> Bump V18.0
